sudo: false
language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - tip
install:
  - go get -v github.com/mattn/goveralls
script:
  - make all
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out
